FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the frontend code
COPY frontend .

# Set environment variables for build time
# Set environment variables for build time
ARG NEXT_PUBLIC_API_URL=https://learning.noleij.ai
ARG NEXTAUTH_URL=https://learning.noleij.ai

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXTAUTH_URL=$NEXTAUTH_URL

# Build the application
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
