FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the frontend code
COPY frontend .

# Set environment variables for build time
ENV NEXT_PUBLIC_API_URL=https://noleij.com
ENV NEXTAUTH_URL=https://noleij.com

# Build the application
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
