"""add_image_url_columns

Revision ID: 46c2c3d97767
Revises: a1acf137c33e
Create Date: 2026-01-12 23:27:00.856802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c2c3d97767'
down_revision: Union[str, None] = 'a1acf137c33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_topic_modules', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('organization_topics', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_topics', 'image_url')
    op.drop_column('organization_topic_modules', 'image_url')
    # ### end Alembic commands ###
